spring:
  application:
    name: gr-zipkin
server:
  port: ${ZIPKIN_PORT:0}
eureka:
  client:
    serviceUrl:
      defaultZone: http://proga.pw:8761/eureka
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
